spring:
  data:
    mongodb:
      database: spring_data
      host: localhost
      port: 27017

---
graphhopper:
  source: "SanktPetersburg.osm.pbf"
  workingDirectory: ${GRAPH_HOPPER_DATA:data}

#TelegramConfig
---
telegrambot:
  botusername: EPAMRidesharing_bot
  bottoken: 760423168:AAERflrOwI7NatFUASyK69bT9z4KLbzkwI0

---
quartz:
  properties:
    notification-scheduling: quartzNotification.properties
    matching-scheduling: quartzMatching.properties

---
notification-settings:
  minutes-before-the-ride-start: 5

---
matching-settings:
  match-frequency-minutes: 1